---
title: Muziekspeler
hero_image: images/banner.png
description: Maak een muziekdoos, zodat je een aantal deuntjes kunt kiezen om bij te ontspannen
version: 4
listed: false
copyedit: false
last_tested: '2023-08-08'
steps:
  - title: Wat ga je maken
  - title: Speel een deuntje
    completion:
      - engaged
  - title: Kies wat deuntjes
  - title: Sla deuntjes over
  - title: Stop of shuffle
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbeter je project
  - title: Wat kun je verder nog doen?
